# Site settings
title: Web Dev & Stuff
email: your-email@domain.com
description: My name is Anton and I am a front end developer. This website is nothing but a place where I can pile up the solutions to web related problems I have not found a solution as well my thoughts that are longer than 140 characters.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://webdevandstuff.com" # the base hostname & protocol for your site
twitter_username: antonk52
github_username:  antonk52

# main menu items
menu:
  - title: Home
    link: "/"
  - title: Work
    link: "/work"
  - title: Contact
    link: "/contact"

# Build settings
markdown: kramdown

# Wordpress flava
permalink: /:title/

# Exclude folling files and dirs
exclude: [src, gulpfile.coffee, package.json, package-lock.json, node_modules]

# I like my styles like I like my hand luggage
sass:
  style: compressed

# Now we can check in layouts
# if we're on post otherwise page
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
